version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      - my_network
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  fastapi_app:
    build: ./database
    container_name: fastapi_app
    networks:
      - my_network
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017

  streamlit_app:
    build: ./UI
    container_name: streamlit_app
    networks:
      - my_network
    ports:
      - "8501:8501"
    depends_on:
      - fastapi_app

networks:
  my_network:

volumes:
  mongodb_data:
